title: Amazing image identifier
hero_image: images/banner.png
description: Build an application that uses machine vision to recognise everyday objects and tell you about them!
version: 4
listed: true
copyedit: true
last_tested: "2020-07-16"
steps:
  - title: Introduction
  - title: Get the starter files
  - title: Run the program
  - title: Load your model
  - title: Predict an image from your computer
  - title: Connect to Wikipedia
  - title: What next?
