title: image-identifier
hero_image: images/banner.png
description: image-identifier description
version: 4
listed: false
copyedit: false
last_tested: "2020-07-16"
steps:
  - title: Introduction
  - title: Get the starter files
  - title: Install the libraries
  - title: Predict an image from your computer
  - title: Connect to Wikipedia
  - title: What's next?
